# Used by mkarchiso to build the live system. @LOCAL_REPO_DIR@ is replaced by
# scripts/build-iso.sh with the freshly built repo.
[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[@REPO_NAME@]
SigLevel = Optional TrustAll
Server = file://@LOCAL_REPO_DIR@

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
